# Estágio de desenvolvimento
FROM node:16-alpine AS development
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
RUN npm ci
COPY --chown=node:node . .
USER node

# Estágio de construção
FROM development AS build
RUN npm run build
ENV NODE_ENV production
RUN npm ci --only=production && npm cache clean --force

# Estágio de produção
FROM node:16-alpine AS production
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist
USER node
CMD [ "node", "dist/main.js" ]
