name: conchayoro-pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: index.html

  deploy_homologation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
          path: index.html

      - name: Deploy to Homologation
        run: aws s3 cp index.html s3://$BUCKET_S3_HOM --recursive --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          BUCKET_S3_HOM: ${{ vars.BUCKET_S3_HOM }}
          AWS_EC2_METADATA_DISABLED: true
          
  deploy_production:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (contains(github.event.head_commit.message, 'feat') || contains(github.event.head_commit.message, 'fix'))

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
          path: index.html

      - name: Deploy to Production
        run: aws s3 cp index.html s3://$BUCKET_S3_PRO --recursive --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          BUCKET_S3_PRO: ${{ vars.BUCKET_S3_PRO }}
          AWS_EC2_METADATA_DISABLED: true
